// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const axios: typeof import('axios')['default']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDispatch: typeof import('react-redux')['useDispatch']
  const useEffect: typeof import('react')['useEffect']
  const useHistory: typeof import('react-router-dom')['useHistory']
  const useLocation: typeof import('react-router-dom')['useLocation']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouteMatch: typeof import('react-router-dom')['useRouteMatch']
  const useSelector: typeof import('react-redux')['useSelector']
  const useState: typeof import('react')['useState']
}
export {}
