/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconBookmark: typeof import('./src/components/icons/IconBookmark.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDelete: typeof import('./src/components/icons/IconDelete.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconLogo: typeof import('./src/components/icons/IconLogo.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconSwitch: typeof import('./src/components/icons/IconSwitch.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Keyboard: typeof import('./src/components/Keyboard.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouteCard: typeof import('./src/components/RouteCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StopCard: typeof import('./src/components/StopCard.vue')['default']
  }
}
